server:
  port: 8103
spring:
  application:
    name: @artifactId@
  datasource:
    url: jdbc:postgresql://localhost:6432/rate_limiter?currentSchema=rate_limiter
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        jdbc:
          batch_size: 5
        order_inserts: false
        order_updates: false
        generate_statistics: false
    open-in-view: false
  flyway:
    enabled: true
    schemas: rate_limiter
resilience4j.ratelimiter:
  instances:
    basicLimiter:
      limit-for-period: 2
      limit-refresh-period: 1s
      timeout-duration: 0