server:
  port: 8102
spring:
  application:
    name: @artifactId@
  datasource:
    url: jdbc:postgresql://localhost:5433/hikari_cp?currentSchema=hikari_cp
    username: postgres
    password: 190695
    hikari:
      maximum-pool-size: 10           # максимальное число одновременных соединений в пуле. Самый важный параметр.
      minimum-idle: 5                 # минимальное число простаивающих соединений.
      connection-timeout: 10000       # сколько ждать свободное соединение (ms) до SQLTransientConnectionException.
      idle-timeout: 600000            # время, после которого простаивающее соединение может быть закрыто (ms).
      max-lifetime: 1800000           # максимальное «жизненное» время соединения; соединения старше этого времени будут перезапущены (ms).
      validation-timeout: 5000        # таймаут для проверки валидности соединения.
      leak-detection-threshold: 2000  # если соединение удерживается дольше этого значения, логируется предупреждение о «утечке» соединения (использовать в dev).
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        jdbc:
          batch_size: 5
        order_inserts: true
        order_updates: true
        generate_statistics: true
    open-in-view: false
  flyway:
    enabled: true
    schemas: hikari_cp
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus,info
  endpoint:
    prometheus:
      enabled: true