spring:
  kafka:
    bootstrap-servers: localhost:9092
    streams:
      application-id: my-stream-kafka-app
      properties:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        state.dir: /tmp/kafka-streams