services:
  pg-rate-limiter:
    image: postgres:17
    container_name: pg-rate-limiter
    ports:
      - "6432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rate_limiter
    volumes:
      - pg_data:/var/lib/postgresql/data
    command: [
      "postgres",
      "-c", "max_connections=60",
      "-c", "shared_buffers=128MB"
    ]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -p 5432" ]
      interval: 10s
      timeout: 5s
      retries: 20

volumes:
  pg_data: